Loading rhel8/default-amp
  Loading requirement: dot rhel8/slurm singularity/current rhel8/global
    cuda/11.4 libpciaccess/0.16/gcc-9.4.0-6fonbj6
    libiconv/1.16/gcc-9.4.0-ahebbov libxml2/2.9.12/gcc-9.4.0-gnknt5e
    ncurses/6.2/gcc-9.4.0-aiirok7 hwloc/2.5.0/gcc-9.4.0-7sqomga
    libevent/2.1.12/gcc-9.4.0-hgny7cm numactl/2.0.14/gcc-9.4.0-52dwc6n
    cuda/11.4.0/gcc-9.4.0-3hnxhjt gdrcopy/2.2/gcc-9.4.0-e4igtfp
    knem/1.1.4/gcc-9.4.0-bpbxgva libnl/3.3.0/gcc-9.4.0-whwhrwb
    rdma-core/34.0/gcc-9.4.0-5eo5n2u ucx/1.11.1/gcc-9.4.0-lktqyl4
    openmpi/4.1.1/gcc-9.4.0-epagguv
Changed directory to /rds/user/tdb47/hpc-work/planning/thinker_private_planning/thinkingtime_exps.

JobID: 58757461
======
Time: Mon Aug 12 09:03:16 BST 2024
Running on master node: gpu-q-1
Current directory: /rds/user/tdb47/hpc-work/planning/thinker_private_planning/thinkingtime_exps

Nodes allocated:
================
gpu-q-1

numtasks=1, numnodes=1, mpi_tasks_per_node=1 (OMP_NUM_THREADS=1)

Executing command:
==================
python run_thinkingtime_exps.py --env_name test --num_episodes 1000 


Initializing env 0 with device cuda
==== ********** STEPS: 0 ********** ====
==== Running agent 10m ====
Traceback (most recent call last):
  File "/rds/user/tdb47/hpc-work/planning/thinker_private_planning/thinkingtime_exps/run_thinkingtime_exps.py", line 44, in <module>
    env = thinker.make(
  File "/rds/user/tdb47/hpc-work/planning/thinker_private_planning/thinker/thinker/main.py", line 561, in make
    return Env(*args, **kwargs)
  File "/rds/user/tdb47/hpc-work/planning/thinker_private_planning/thinker/thinker/main.py", line 101, in __init__
    env = env_fn()
  File "/rds/user/tdb47/hpc-work/planning/thinker_private_planning/thinker/thinker/wrapper.py", line 235, in <lambda>
    fn(**args), 
  File "/rds/user/tdb47/hpc-work/planning/env/lib/python3.9/site-packages/gym/envs/registration.py", line 676, in make
    return registry.make(id, **kwargs)
  File "/rds/user/tdb47/hpc-work/planning/env/lib/python3.9/site-packages/gym/envs/registration.py", line 490, in make
    versions = self.env_specs.versions(namespace, name)
  File "/rds/user/tdb47/hpc-work/planning/env/lib/python3.9/site-packages/gym/envs/registration.py", line 220, in versions
    self._assert_name_exists(namespace, name)
  File "/rds/user/tdb47/hpc-work/planning/env/lib/python3.9/site-packages/gym/envs/registration.py", line 297, in _assert_name_exists
    raise error.NameNotFound(message)
gym.error.NameNotFound: Environment `Sokoban-test_clean_0000` doesn't exist. Did you mean: `Sokoban-plantest_clean_0000`?
